# ????????? Java ??????? Docker Database
spring.datasource.url=jdbc:postgresql://localhost:5432/comic_reader
spring.datasource.username=jomjuthamast
spring.datasource.password=753951a753951

# ??? Hibernate ?????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=1234